### ISSUE TITLE
运行 `python cli.py`时发生错误

### ISSUE THREAD

**Issue by zhaostarr** [wxywb/history_rag#43]
你好。我的环境信息：操作系统：Windows 11
开发工具：VSCode
Python 版本：python-3.11.8
llama-index 版本：0.9.39
-------
Issue: 在命令行模式下(powershell和cmd都是)运行 `python cli.py`时发生错误
ImportError: cannot import name 'ChatMessage' from 'llama_index.core.llms' (C:\Users\zhaos\AppData\Roaming\Python\Python311\site-packages\llama_index\core\llms\__init__.py)

谢谢！
ZS

**Comment by wxywb** [comment]
![截屏2024-02-18 下午11 32 14](https://github.com/wxywb/history_rag/assets/5432721/7c719cbb-17e2-4e4c-ae5a-7a6ad87e4a1c)
哪个地方从llama_index.core.llms import ChatMessage？

**Comment by CL-matt** [comment]
> ![截屏2024-02-18 下午11 32 14](https://private-user-images.githubusercontent.com/5432721/305727246-7c719cbb-17e2-4e4c-ae5a-7a6ad87e4a1c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgyOTQ3OTcsIm5iZiI6MTcwODI5NDQ5NywicGF0aCI6Ii81NDMyNzIxLzMwNTcyNzI0Ni03YzcxOWNiYi0xN2UyLTRlNGMtYWU1YS03YTZhZDg3ZTRhMWMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIxOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMThUMjIxNDU3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZGYzYmJjNGYyYzIxNGVmZDRiZTgyMzNiZjIzYmViZjllZTBjODBhM2UzM2ZlOTRiMmVjMmI2YWE5ZTViOTdmZSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.R_-ehszGG2cMKNS3-fdceoS3_Ah8TC6XILjjYMsnGr0) 哪个地方从llama_index.core.llms import ChatMessage？

Traceback (most recent call last):
  File "F:\code\RAG\history_rag\cli.py", line 1, in <module>
    from executor import MilvusExecutor
  File "F:\code\RAG\history_rag\executor.py", line 12, in <module>
    from llama_index import ServiceContext, StorageContext
  File "E:\ananconda\envs\RAg\Lib\site-packages\llama_index\__init__.py", line 13, in <module>
    from llama_index.callbacks.global_handlers import set_global_handler
  File "E:\ananconda\envs\RAg\Lib\site-packages\llama_index\callbacks\__init__.py", line 7, in <module>
    from .token_counting import TokenCountingHandler
  File "E:\ananconda\envs\RAg\Lib\site-packages\llama_index\callbacks\token_counting.py", line 6, in <module>
    from llama_index.utilities.token_counting import TokenCounter
  File "E:\ananconda\envs\RAg\Lib\site-packages\llama_index\utilities\token_counting.py", line 6, in <module>
    from llama_index.llms import ChatMessage, MessageRole
  File "E:\ananconda\envs\RAg\Lib\site-packages\llama_index\llms\__init__.py", line 14, in <module>
    from llama_index.llms.anyscale import Anyscale
  File "E:\ananconda\envs\RAg\Lib\site-packages\llama_index\llms\anyscale.py", line 10, in <module>
    from llama_index.llms.openai import OpenAI
  File "E:\ananconda\envs\RAg\Lib\site-packages\llama_index\llms\openai\__init__.py", line 1, in <module>
    from llama_index.llms.openai.base import AsyncOpenAI, OpenAI, SyncOpenAI, Tokenizer
  File "E:\ananconda\envs\RAg\Lib\site-packages\llama_index\llms\openai\base.py", line 28, in <module>
    from llama_index.core.callbacks import CallbackManager
  File "E:\ananconda\envs\RAg\Lib\site-packages\llama_index\core\callbacks\__init__.py", line 4, in <module>
    from .token_counting import TokenCountingHandler
  File "E:\ananconda\envs\RAg\Lib\site-packages\llama_index\core\callbacks\token_counting.py", line 6, in <module>
    from llama_index.core.utilities.token_counting import TokenCounter
  File "E:\ananconda\envs\RAg\Lib\site-packages\llama_index\core\utilities\token_counting.py", line 6, in <module>
    **from llama_index.core.llms import ChatMessage, MessageRole**
ImportError: cannot import name 'ChatMessage' from 'llama_index.core.llms' (E:\ananconda\envs\RAg\Lib\site-packages\llama_index\core\llms\__init__.py) 
大佬我也遇到这个问题了，你看倒数第三行‘’from llama_index.core.llms import ChatMessage, MessageRole''

**Comment by wxywb** [comment]
@CL-matt  看一下你的`E:\ananconda\envs\RAg\Lib\site-packages\llama_index\core\`我没看见有utilities这个文件夹
<img width="915" alt="截屏2024-02-19 上午10 06 23" src="https://github.com/wxywb/history_rag/assets/5432721/d6435401-8247-4897-a279-f3f0780d2af2">
顺便 pip list|grep llama 我再确认一下你的版本

**Comment by CL-matt** [comment]
@wxywb  
![imagen](https://github.com/wxywb/history_rag/assets/84998576/d2f2dbe0-20e1-43d8-8af8-40f58e594a54)
utilities文件夹是有的.
![imagen](https://github.com/wxywb/history_rag/assets/84998576/9ea84199-fcae-42ab-af5a-c444cf3536e4)

![imagen](https://github.com/wxywb/history_rag/assets/84998576/d7bae67c-5ed3-43d1-8e07-3212e20eef50)

**Comment by wxywb** [comment]
@CL-matt 这样你把这些全部pip uninstall  了，然后只 pip install llama-index==0.9.39

**Comment by zhaostarr** [comment]
搞定了，删除了python，重新构建了虚拟环境。主要是版本不一致。谢谢大佬
