### ISSUE TITLE
小白遇到Milvus服务器的问题，恳请解答

### ISSUE THREAD

**Issue by zizu2024** [wxywb/history_rag#44]
大神你好，在执行python cli.py后，遇到如下问题，感觉是Milvus服务器没有运行，但自己在这方面知识储备几乎为0，请大神指教，多谢：
(rag) 选择[milvus|pipeline]方案
(rag) milvus
(rag) milvus模式已选择
  1.使用`build data/history_24/baihuasanguozhi.txt`来进行知识库构建。
  2.已有索引可以使用`ask`进行提问, `-d`参数以debug模式进入。
  3.删除已有索引可以使用`remove baihuasanguozhi.txt`。
(rag) ask
Failed to create new connection using: b1afc9fc359640d19a58706da83db8a4
Traceback (most recent call last):
  File "/app/cli.py", line 120, in <module>
    cli.run()
  File "/app/cli.py", line 53, in run
    self.parse_input(command_text)
  File "/app/cli.py", line 74, in parse_input
    self.question_answer()
  File "/app/cli.py", line 99, in question_answer
    self._executor.build_query_engine()
  File "/app/executor.py", line 196, in build_query_engine
    self._get_index()
  File "/app/executor.py", line 186, in _get_index
    vector_store = MilvusVectorStore(
                   ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/llama_index/vector_stores/milvus.py", line 137, in __init__
    self.milvusclient = MilvusClient(
                        ^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pymilvus/milvus_client/milvus_client.py", line 59, in __init__
    self._using = self._create_connection(
                  ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pymilvus/milvus_client/milvus_client.py", line 551, in _create_connection
    raise ex from ex
  File "/usr/local/lib/python3.11/site-packages/pymilvus/milvus_client/milvus_client.py", line 548, in _create_connection
    connections.connect(using, user, password, db_name, token, uri=uri, **kwargs)
  File "/usr/local/lib/python3.11/site-packages/pymilvus/orm/connections.py", line 414, in connect
    connect_milvus(**kwargs, user=user, password=password, token=token, db_name=db_name)
  File "/usr/local/lib/python3.11/site-packages/pymilvus/orm/connections.py", line 365, in connect_milvus
    gh._wait_for_channel_ready(timeout=timeout)
  File "/usr/local/lib/python3.11/site-packages/pymilvus/client/grpc_handler.py", line 146, in _wait_for_channel_ready
    raise MilvusException(
pymilvus.exceptions.MilvusException: <MilvusException: (code=2, message=Fail connecting to server on localhost:19530. Timeout)>

**Comment by wxywb** [comment]
我也感觉是milvus没有启动，看一下容器内的milvus服务呢
```bash 
docker ps
```

**Comment by zizu2024** [comment]
方便加下联系方式点对点与您咨询吗，谢

wxywb ***@***.***> 于2024年2月19日周一 14:29写道：
