### ISSUE TITLE
RuntimeError: {'code': 90019, 'message': 'Pipeline server error: call server failed, msg=internal error'}

### ISSUE THREAD

**Issue by Yi-Lyu** [wxywb/history_rag#53]
➜  history_rag git:(master) ✗ python3 cli.py
     ___  ___   _____         _   _   _   _____   _____   _____   _____   __    __
    /   |/   | |  _  \       | | | | | | /  ___/ |_   _| /  _  \ |  _  \  \ \  / /
   / /|   /| | | |_| |       | |_| | | | | |___    | |   | | | | | |_| |   \ \/ /
  / / |__/ | | |  _  /       |  _  | | | \___  \   | |   | | | | |  _  /    \  /
 / /       | | | | \ \       | | | | | |  ___| |   | |   | |_| | | | \ \    / /
/_/        |_| |_|  \_\      |_| |_| |_| /_____/   |_|   \_____/ |_|  \_\  /_/

**********************
*    Version:2.0     *
**********************
* Author:Bruce Young *
**********************

(rag) 选择[milvus|pipeline]方案
(rag) pipeline
Embeddings have been explicitly disabled. Using MockEmbedding.
(rag) pipeline模式已选择, 使用`build https://raw.githubusercontent.com/wxywb/history_rag/master/data/history_24/baihuasanguozhi.txt`来进行知识库构建。
  1.使用`build https://raw.githubusercontent.com/wxywb/history_rag/master/data/history_24/baihuasanguozhi.txt`来进行知 识库构建。
  2.已有索引可以使用`ask`进行提问, `-d`参数以debug模式进入。
  3.删除已有索引可以使用`remove baihuasanguozhi.txt`。
(rag) build https://raw.githubusercontent.com/Yi-Lyu/MyVimConfig/master/20240228.txt
Traceback (most recent call last):
  File "/root/code/history_rag/cli.py", line 120, in <module>
    cli.run()
  File "/root/code/history_rag/cli.py", line 53, in run
    self.parse_input(command_text)
  File "/root/code/history_rag/cli.py", line 65, in parse_input
    self.build_index(path=commands[1], overwrite=False)
  File "/root/code/history_rag/cli.py", line 92, in build_index
    self._executor.build_index(path, overwrite)
  File "/root/code/history_rag/executor.py", line 328, in build_index
    self.index.insert_doc_url(
  File "/root/code/history_rag/custom/zilliz/base.py", line 135, in insert_doc_url
    raise RuntimeError(response_dict)
RuntimeError: {'code': 90019, 'message': 'Pipeline server error: call server failed, msg=internal error'}

**Comment by wxywb** [comment]
你重新启动一下，试一下ask，看一下能正常问答吗
