### ISSUE TITLE
输入ask后报错

### ISSUE THREAD

**Issue by moming975** [wxywb/history_rag#61]
索引已经生成过了，报错如下

`python3 cli.py
     ___  ___   _____         _   _   _   _____   _____   _____   _____   __    __ 
    /   |/   | |  _  \       | | | | | | /  ___/ |_   _| /  _  \ |  _  \  \ \  / / 
   / /|   /| | | |_| |       | |_| | | | | |___    | |   | | | | | |_| |   \ \/ /  
  / / |__/ | | |  _  /       |  _  | | | \___  \   | |   | | | | |  _  /    \  /   
 / /       | | | | \ \       | | | | | |  ___| |   | |   | |_| | | | \ \    / /    
/_/        |_| |_|  \_\      |_| |_| |_| /_____/   |_|   \_____/ |_|  \_\  /_/     

**********************
*    Version:2.0     *
**********************
* Author:Bruce Young *
**********************

(rag) 选择[milvus|pipeline]方案
(rag) milvus
(rag) milvus模式已选择
  1.使用`build data/history_24/baihuasanguozhi.txt`来进行知识库构建。
  2.已有索引可以使用`ask`进行提问, `-d`参数以debug模式进入。
  3.删除已有索引可以使用`remove baihuasanguozhi.txt`。
(rag) ask -d
Traceback (most recent call last):
  File "/home/pushsoft/cywTest/history_rag/cli.py", line 120, in <module>
    cli.run()
  File "/home/pushsoft/cywTest/history_rag/cli.py", line 53, in run
    self.parse_input(command_text)
  File "/home/pushsoft/cywTest/history_rag/cli.py", line 74, in parse_input
    self.question_answer()
  File "/home/pushsoft/cywTest/history_rag/cli.py", line 99, in question_answer
    self._executor.build_query_engine()
  File "/home/pushsoft/cywTest/history_rag/executor.py", line 201, in build_query_engine
    self.query_engine = self.index.as_query_engine(node_postprocessors=[
  File "/home/pushsoft/.local/lib/python3.10/site-packages/llama_index/indices/base.py", line 350, in as_query_engine
    from llama_index.query_engine.retriever_query_engine import RetrieverQueryEngine
  File "/home/pushsoft/.local/lib/python3.10/site-packages/llama_index/query_engine/__init__.py", line 27, in <module>
    from llama_index.query_engine.router_query_engine import (
  File "/home/pushsoft/.local/lib/python3.10/site-packages/llama_index/query_engine/router_query_engine.py", line 24, in <module>
    from llama_index.selectors.utils import get_selector_from_context
  File "/home/pushsoft/.local/lib/python3.10/site-packages/llama_index/selectors/__init__.py", line 3, in <module>
    from llama_index.selectors.pydantic_selectors import (
  File "/home/pushsoft/.local/lib/python3.10/site-packages/llama_index/selectors/pydantic_selectors.py", line 10, in <module>
    from llama_index.program.openai_program import OpenAIPydanticProgram
  File "/home/pushsoft/.local/lib/python3.10/site-packages/llama_index/program/__init__.py", line 5, in <module>
    from llama_index.program.openai_program import OpenAIPydanticProgram
  File "/home/pushsoft/.local/lib/python3.10/site-packages/llama_index/program/openai_program.py", line 4, in <module>
    from llama_index.agent.openai.utils import resolve_tool_choice
  File "/home/pushsoft/.local/lib/python3.10/site-packages/llama_index/agent/__init__.py", line 2, in <module>
    from llama_index.agent.custom.pipeline_worker import QueryPipelineAgentWorker
  File "/home/pushsoft/.local/lib/python3.10/site-packages/llama_index/agent/custom/pipeline_worker.py", line 27, in <module>
    from llama_index.query_pipeline.components.agent import (
  File "/home/pushsoft/.local/lib/python3.10/site-packages/llama_index/query_pipeline/__init__.py", line 24, in <module>
    from llama_index.query_pipeline.query import InputKeys, OutputKeys, QueryPipeline
  File "/home/pushsoft/.local/lib/python3.10/site-packages/llama_index/query_pipeline/query.py", line 7, in <module>
    import networkx
  File "/usr/local/lib/python3.10/dist-packages/networkx/__init__.py", line 20, in <module>
    from networkx.utils.backends import _dispatch
  File "/usr/local/lib/python3.10/dist-packages/networkx/utils/backends.py", line 132, in <module>
    backends = _get_backends("networkx.plugins")
  File "/usr/local/lib/python3.10/dist-packages/networkx/utils/backends.py", line 106, in _get_backends
    items = entry_points(group=group)
  File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 1021, in entry_points
    return SelectableGroups.load(eps).select(**params)
  File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 459, in load
    ordered = sorted(eps, key=by_group)
  File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 1018, in <genexpr>
    eps = itertools.chain.from_iterable(
  File "/usr/lib/python3.10/importlib/metadata/_itertools.py", line 16, in unique_everseen
    k = key(element)
  File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 943, in _normalized_name
    or super()._normalized_name
  File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 622, in _normalized_name
    return Prepared.normalize(self.name)
  File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 871, in normalize
    return re.sub(r"[-_.]+", "-", name).lower().replace('-', '_')
  File "/usr/lib/python3.10/re.py", line 209, in sub
    return _compile(pattern, flags).sub(repl, string, count)
TypeError: expected string or bytes-like objec`

**Comment by wxywb** [comment]
我认为你遇到的是这个问题，这个问题应该和llamaindex或者history_rag无关
https://stackoverflow.com/questions/75925323/how-can-i-fix-importlib-on-python3-10-so-that-it-can-call-entry-points-properl

**Comment by moming975** [comment]
按楼上的链接，最后尝试把networkx==2.8.8换了个低版本的，好了
