### ISSUE TITLE
在进入ask模式时出错

### ISSUE THREAD

**Issue by LichengKang2000** [wxywb/history_rag#69]
您好！我正在使用llama-index==0.9.39运行您的RAG程序，但是运行过程中发现llama-index这个包存在很多问题，靠chatgpt解决了一些，但是现在的问题我无法解决，报错如下：
(rag) ask
Traceback (most recent call last):
  File "D:\ProgramData\atlasrag\history_rag-master\history_rag-master\cli.py", line 120, in <module>
    cli.run()
  File "D:\ProgramData\atlasrag\history_rag-master\history_rag-master\cli.py", line 53, in run
    self.parse_input(command_text)
  File "D:\ProgramData\atlasrag\history_rag-master\history_rag-master\cli.py", line 74, in parse_input
    self.question_answer()
  File "D:\ProgramData\atlasrag\history_rag-master\history_rag-master\cli.py", line 99, in question_answer
    self._executor.build_query_engine()
  File "D:\ProgramData\atlasrag\history_rag-master\history_rag-master\executor.py", line 337, in build_query_engine
    self.query_engine = self.index.as_query_engine(
  File "D:\ProgramData\anaconda3\envs\python39\lib\site-packages\llama_index\indices\base.py", line 350, in as_query_engine
    from llama_index.query_engine.retriever_query_engine import RetrieverQueryEngine
  File "D:\ProgramData\anaconda3\envs\python39\lib\site-packages\llama_index\query_engine\__init__.py", line 27, in <module>
    from llama_index.query_engine.router_query_engine import (
  File "D:\ProgramData\anaconda3\envs\python39\lib\site-packages\llama_index\query_engine\router_query_engine.py", line 24, in <module>
    from llama_index.selectors.utils import get_selector_from_context
  File "D:\ProgramData\anaconda3\envs\python39\lib\site-packages\llama_index\selectors\__init__.py", line 3, in <module>
    from llama_index.selectors.pydantic_selectors import (
  File "D:\ProgramData\anaconda3\envs\python39\lib\site-packages\llama_index\selectors\pydantic_selectors.py", line 10, in <module>
    from llama_index.program.openai_program import OpenAIPydanticProgram
  File "D:\ProgramData\anaconda3\envs\python39\lib\site-packages\llama_index\program\__init__.py", line 5, in <module>
    from llama_index.program.openai_program import OpenAIPydanticProgram
  File "D:\ProgramData\anaconda3\envs\python39\lib\site-packages\llama_index\program\openai_program.py", line 4, in <module>
    from llama_index.agent.openai.utils import resolve_tool_choice
  File "D:\ProgramData\anaconda3\envs\python39\lib\site-packages\llama_index\agent\__init__.py", line 2, in <module>
    from llama_index.agent.custom.pipeline_worker import QueryPipelineAgentWorker
  File "D:\ProgramData\anaconda3\envs\python39\lib\site-packages\llama_index\agent\custom\pipeline_worker.py", line 27, in <module>
    from llama_index.query_pipeline.components.agent import (
  File "D:\ProgramData\anaconda3\envs\python39\lib\site-packages\llama_index\query_pipeline\__init__.py", line 3, in <module>
    from llama_index.core.query_pipeline.components import (
  File "D:\ProgramData\anaconda3\envs\python39\lib\site-packages\llama_index\core\query_pipeline\components\__init__.py", line 13, in <module>
    from llama_index.core.query_pipeline.components.router import (
  File "D:\ProgramData\anaconda3\envs\python39\lib\site-packages\llama_index\core\query_pipeline\components\router.py", line 6, in <module>
    from llama_index.core.base.base_selector import BaseSelector
  File "D:\ProgramData\anaconda3\envs\python39\lib\site-packages\llama_index\core\base\base_selector.py", line 11, in <module>
    from llama_index.core.tools.types import ToolMetadata
  File "D:\ProgramData\anaconda3\envs\python39\lib\site-packages\llama_index\core\tools\__init__.py", line 6, in <module>
    from llama_index.core.tools.query_plan import QueryPlanTool
  File "D:\ProgramData\anaconda3\envs\python39\lib\site-packages\llama_index\core\tools\query_plan.py", line 6, in <module>
    from llama_index.core.response_synthesizers import (
  File "D:\ProgramData\anaconda3\envs\python39\lib\site-packages\llama_index\core\response_synthesizers\__init__.py", line 3, in <module>
    from llama_index.core.response_synthesizers.accumulate import Accumulate
  File "D:\ProgramData\anaconda3\envs\python39\lib\site-packages\llama_index\core\response_synthesizers\accumulate.py", line 6, in <module>
    from llama_index.core.indices.prompt_helper import PromptHelper
  File "D:\ProgramData\anaconda3\envs\python39\lib\site-packages\llama_index\core\indices\__init__.py", line 4, in <module>
    from llama_index.core.indices.composability.graph import ComposableGraph
  File "D:\ProgramData\anaconda3\envs\python39\lib\site-packages\llama_index\core\indices\composability\__init__.py", line 4, in <module>
    from llama_index.core.indices.composability.graph import ComposableGraph
  File "D:\ProgramData\anaconda3\envs\python39\lib\site-packages\llama_index\core\indices\composability\graph.py", line 7, in <module>
    from llama_index.core.indices.base import BaseIndex
  File "D:\ProgramData\anaconda3\envs\python39\lib\site-packages\llama_index\core\indices\base.py", line 10, in <module>
    from llama_index.core.chat_engine.types import BaseChatEngine, ChatMode
  File "D:\ProgramData\anaconda3\envs\python39\lib\site-packages\llama_index\core\chat_engine\__init__.py", line 1, in <module>
    from llama_index.core.chat_engine.condense_plus_context import (
  File "D:\ProgramData\anaconda3\envs\python39\lib\site-packages\llama_index\core\chat_engine\condense_plus_context.py", line 8, in <module>
    from llama_index.core.chat_engine.types import (
  File "D:\ProgramData\anaconda3\envs\python39\lib\site-packages\llama_index\core\chat_engine\types.py", line 10, in <module>
    from llama_index.core.tools import ToolOutput
ImportError: cannot import name 'ToolOutput' from partially initialized module 'llama_index.core.tools' (most likely due to a circular import) (D:\ProgramData\anaconda3\envs\python39\lib\site-packages\llama_index\core\tools\__init__.py)
这似乎是出现了一个循环导入问题，但\core\tools\__init__.py中ToolOutput的导入指向了\core\tools\types.py，而ToolOutput确实是在types.py里面定义的，看上去没有问题。可以帮我看一下问题到底出在哪里，如何解决呢？

**Comment by wxywb** [comment]
pip list |grep llama

**Comment by LichengKang2000** [comment]
![image](https://github.com/wxywb/history_rag/assets/121110613/7741f0d0-6d72-491f-a87c-cdb9029c2b3e)
我用的是win11

**Comment by wxywb** [comment]
你这个明显是0.9和0.10混在一起了，把它们都删了重新装一下0.9.39 或者你用virualenv搞一个新环境
