### ISSUE TITLE
ModuleNotFoundError: No module named 'llama_index.vector_stores   现在遇到模型找不到的问题，这个是向量数据库没配置的原因吗，我在docker里运行的

### ISSUE THREAD

**Issue by taiyi7** [wxywb/history_rag#81]
python cli.py 
[nltk_data] Downloading package punkt_tab to
[nltk_data]     /usr/local/lib/python3.10/site-
[nltk_data]     packages/llama_index/core/_static/nltk_cache...
[nltk_data]   Unzipping tokenizers/punkt_tab.zip.
Traceback (most recent call last):
  File "/mnt/workspace/rag/history_rag/cli.py", line 1, in <module>
    from executor import MilvusExecutor
  File "/mnt/workspace/rag/history_rag/executor.py", line 18, in <module>
    from llama_index.vector_stores.milvus import MilvusVectorStore
ModuleNotFoundError: No module named 'llama_index.vector_stores'

**Comment by taiyi7** [comment]
安装向量数据库这个操作报错，本身是运行在docker上的

root@dsw-134201-677857dbc5-th26f:/mnt/workspace/rag/history_rag# cd db
root@dsw-134201-677857dbc5-th26f:/mnt/workspace/rag/history_rag/db# sudo docker compose up -d
sudo: docker：找不到命令
root@dsw-134201-677857dbc5-th26f:/mnt/workspace/rag/history_rag/db# ls
docker-compose.yml
root@dsw-134201-677857dbc5-th26f:/mnt/workspace/rag/history_rag/db#
